// <auto-generated />
using System;
using DataLager;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataLager.Migrations
{
    [DbContext(typeof(ApplikationDbContext))]
    partial class ApplikationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EntitetsLager.Anvandare", b =>
                {
                    b.Property<int>("AnvandarID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AnvandarID"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<string>("Anvandarnamn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("HemmarestaurangID")
                        .HasColumnType("int");

                    b.Property<string>("Losenord")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Roll")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("AnvandarID");

                    b.HasIndex("HemmarestaurangID");

                    b.ToTable("Anvandare");
                });

            modelBuilder.Entity("EntitetsLager.Bestallning", b =>
                {
                    b.Property<int>("BestallningsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BestallningsID"));

                    b.Property<int>("AnvandarID")
                        .HasColumnType("int");

                    b.Property<string>("BestallningsTyp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("Betald")
                        .HasColumnType("bit");

                    b.Property<int?>("BokningsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("KundID")
                        .HasColumnType("int");

                    b.Property<int>("PoangTilldelas")
                        .HasColumnType("int");

                    b.Property<int>("RestaurangID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("Tid")
                        .HasColumnType("time");

                    b.Property<decimal>("TotalSumma")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Utkorare")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("BestallningsID");

                    b.HasIndex("AnvandarID");

                    b.HasIndex("BokningsID");

                    b.HasIndex("KundID");

                    b.HasIndex("RestaurangID");

                    b.ToTable("Bestallningar");
                });

            modelBuilder.Entity("EntitetsLager.BestallningsRad", b =>
                {
                    b.Property<int>("BestallningsRadID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BestallningsRadID"));

                    b.Property<int>("Antal")
                        .HasColumnType("int");

                    b.Property<int>("BestallningsID")
                        .HasColumnType("int");

                    b.Property<int>("BestallningsID1")
                        .HasColumnType("int");

                    b.Property<int>("MenyID")
                        .HasColumnType("int");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Summa")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("BestallningsRadID");

                    b.HasIndex("BestallningsID1");

                    b.HasIndex("MenyID");

                    b.ToTable("BestallningsRader");
                });

            modelBuilder.Entity("EntitetsLager.Bokning", b =>
                {
                    b.Property<int>("BokningsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BokningsID"));

                    b.Property<int>("AntalGaster")
                        .HasColumnType("int");

                    b.Property<int?>("AnvandarID")
                        .HasColumnType("int");

                    b.Property<string>("BokningsTyp")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("BordID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("KundID")
                        .HasColumnType("int");

                    b.Property<int>("RestaurangID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SkapadDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Specialinformation")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<TimeSpan>("Tid")
                        .HasColumnType("time");

                    b.HasKey("BokningsID");

                    b.HasIndex("AnvandarID");

                    b.HasIndex("BordID");

                    b.HasIndex("KundID");

                    b.HasIndex("RestaurangID");

                    b.ToTable("Bokningar");
                });

            modelBuilder.Entity("EntitetsLager.Bord", b =>
                {
                    b.Property<int>("BordID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BordID"));

                    b.Property<int>("AntalPlatser")
                        .HasColumnType("int");

                    b.Property<string>("Bordkod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("RestaurangID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("BordID");

                    b.HasIndex("RestaurangID");

                    b.ToTable("Bord");
                });

            modelBuilder.Entity("EntitetsLager.Kund", b =>
                {
                    b.Property<int>("KundID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KundID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("HemmarestaurangID")
                        .HasColumnType("int");

                    b.Property<string>("LojalitetsNiva")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("LojalitetsPoang")
                        .HasColumnType("int");

                    b.Property<string>("Namn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("RegionID")
                        .HasColumnType("int");

                    b.Property<DateTime>("SkapadDatum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("KundID");

                    b.HasIndex("HemmarestaurangID");

                    b.HasIndex("RegionID");

                    b.ToTable("Kunder");
                });

            modelBuilder.Entity("EntitetsLager.LojalitetsTransaktion", b =>
                {
                    b.Property<int>("LojalitetsTransaktionsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LojalitetsTransaktionsID"));

                    b.Property<int?>("BestallningsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("KundID")
                        .HasColumnType("int");

                    b.Property<int>("PoangAnvanda")
                        .HasColumnType("int");

                    b.Property<int>("PoangSaldo")
                        .HasColumnType("int");

                    b.Property<int>("PoangTillagda")
                        .HasColumnType("int");

                    b.HasKey("LojalitetsTransaktionsID");

                    b.HasIndex("BestallningsID");

                    b.HasIndex("KundID");

                    b.ToTable("LojalitetsTransaktioner");
                });

            modelBuilder.Entity("EntitetsLager.Meny", b =>
                {
                    b.Property<int>("MenyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MenyID"));

                    b.Property<bool>("Aktiv")
                        .HasColumnType("bit");

                    b.Property<bool>("ArGrundmeny")
                        .HasColumnType("bit");

                    b.Property<string>("Beskrivning")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Kategori")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Pris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Rattnamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("MenyID");

                    b.ToTable("Menyer");
                });

            modelBuilder.Entity("EntitetsLager.Region", b =>
                {
                    b.Property<int>("RegionID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RegionID"));

                    b.Property<int>("AntalRestauranger")
                        .HasColumnType("int");

                    b.Property<string>("Regionnamn")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RegionID");

                    b.ToTable("Regioner");
                });

            modelBuilder.Entity("EntitetsLager.Restaurang", b =>
                {
                    b.Property<int>("RestaurangID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurangID"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Oppettider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RegionID")
                        .HasColumnType("int");

                    b.Property<string>("Restaurangnamn")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("RestaurangID");

                    b.ToTable("Restauranger");
                });

            modelBuilder.Entity("EntitetsLager.RestaurangMeny", b =>
                {
                    b.Property<int>("RestaurangMenyID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RestaurangMenyID"));

                    b.Property<decimal?>("LokalPris")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("MenyID")
                        .HasColumnType("int");

                    b.Property<int>("RestaurangID")
                        .HasColumnType("int");

                    b.Property<bool>("Tillganglig")
                        .HasColumnType("bit");

                    b.HasKey("RestaurangMenyID");

                    b.HasIndex("MenyID");

                    b.HasIndex("RestaurangID");

                    b.ToTable("RestaurangMenyer");
                });

            modelBuilder.Entity("EntitetsLager.Systemlogg", b =>
                {
                    b.Property<int>("LoggID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LoggID"));

                    b.Property<int?>("AnvandarID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<string>("Handelse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("IPAdress")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<string>("Modul")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<TimeSpan>("Tid")
                        .HasColumnType("time");

                    b.HasKey("LoggID");

                    b.HasIndex("AnvandarID");

                    b.ToTable("Systemloggar");
                });

            modelBuilder.Entity("EntitetsLager.Transaktion", b =>
                {
                    b.Property<int>("TransaktionsID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TransaktionsID"));

                    b.Property<decimal>("AlkoholSumma")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AnvandarID")
                        .HasColumnType("int");

                    b.Property<int>("BestallningsID")
                        .HasColumnType("int");

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("MatSumma")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Moms")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RestaurangID")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalSumma")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("TransaktionsID");

                    b.HasIndex("AnvandarID");

                    b.HasIndex("BestallningsID");

                    b.HasIndex("RestaurangID");

                    b.ToTable("Transaktioner");
                });

            modelBuilder.Entity("EntitetsLager.Anvandare", b =>
                {
                    b.HasOne("EntitetsLager.Restaurang", "Hemmarestaurang")
                        .WithMany()
                        .HasForeignKey("HemmarestaurangID");

                    b.Navigation("Hemmarestaurang");
                });

            modelBuilder.Entity("EntitetsLager.Bestallning", b =>
                {
                    b.HasOne("EntitetsLager.Anvandare", "Anvandare")
                        .WithMany()
                        .HasForeignKey("AnvandarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntitetsLager.Bokning", "Bokning")
                        .WithMany()
                        .HasForeignKey("BokningsID");

                    b.HasOne("EntitetsLager.Kund", "Kund")
                        .WithMany()
                        .HasForeignKey("KundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntitetsLager.Restaurang", "Restaurang")
                        .WithMany()
                        .HasForeignKey("RestaurangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anvandare");

                    b.Navigation("Bokning");

                    b.Navigation("Kund");

                    b.Navigation("Restaurang");
                });

            modelBuilder.Entity("EntitetsLager.BestallningsRad", b =>
                {
                    b.HasOne("EntitetsLager.Bestallning", "Bestallning")
                        .WithMany()
                        .HasForeignKey("BestallningsID1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntitetsLager.Meny", "Meny")
                        .WithMany()
                        .HasForeignKey("MenyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bestallning");

                    b.Navigation("Meny");
                });

            modelBuilder.Entity("EntitetsLager.Bokning", b =>
                {
                    b.HasOne("EntitetsLager.Anvandare", "Anvandare")
                        .WithMany()
                        .HasForeignKey("AnvandarID");

                    b.HasOne("EntitetsLager.Bord", "Bord")
                        .WithMany()
                        .HasForeignKey("BordID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntitetsLager.Kund", "Kund")
                        .WithMany()
                        .HasForeignKey("KundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntitetsLager.Restaurang", "Restaurang")
                        .WithMany()
                        .HasForeignKey("RestaurangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anvandare");

                    b.Navigation("Bord");

                    b.Navigation("Kund");

                    b.Navigation("Restaurang");
                });

            modelBuilder.Entity("EntitetsLager.Bord", b =>
                {
                    b.HasOne("EntitetsLager.Restaurang", "Restaurang")
                        .WithMany()
                        .HasForeignKey("RestaurangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Restaurang");
                });

            modelBuilder.Entity("EntitetsLager.Kund", b =>
                {
                    b.HasOne("EntitetsLager.Restaurang", "Hemmarestaurang")
                        .WithMany()
                        .HasForeignKey("HemmarestaurangID");

                    b.HasOne("EntitetsLager.Region", "Region")
                        .WithMany()
                        .HasForeignKey("RegionID");

                    b.Navigation("Hemmarestaurang");

                    b.Navigation("Region");
                });

            modelBuilder.Entity("EntitetsLager.LojalitetsTransaktion", b =>
                {
                    b.HasOne("EntitetsLager.Bestallning", "Bestallning")
                        .WithMany()
                        .HasForeignKey("BestallningsID");

                    b.HasOne("EntitetsLager.Kund", "Kund")
                        .WithMany()
                        .HasForeignKey("KundID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bestallning");

                    b.Navigation("Kund");
                });

            modelBuilder.Entity("EntitetsLager.RestaurangMeny", b =>
                {
                    b.HasOne("EntitetsLager.Meny", "Meny")
                        .WithMany()
                        .HasForeignKey("MenyID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntitetsLager.Restaurang", "Restaurang")
                        .WithMany()
                        .HasForeignKey("RestaurangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Meny");

                    b.Navigation("Restaurang");
                });

            modelBuilder.Entity("EntitetsLager.Systemlogg", b =>
                {
                    b.HasOne("EntitetsLager.Anvandare", "Anvandare")
                        .WithMany()
                        .HasForeignKey("AnvandarID");

                    b.Navigation("Anvandare");
                });

            modelBuilder.Entity("EntitetsLager.Transaktion", b =>
                {
                    b.HasOne("EntitetsLager.Anvandare", "Anvandare")
                        .WithMany()
                        .HasForeignKey("AnvandarID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntitetsLager.Bestallning", "Bestallning")
                        .WithMany()
                        .HasForeignKey("BestallningsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EntitetsLager.Restaurang", "Restaurang")
                        .WithMany()
                        .HasForeignKey("RestaurangID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Anvandare");

                    b.Navigation("Bestallning");

                    b.Navigation("Restaurang");
                });
#pragma warning restore 612, 618
        }
    }
}
